###
#
# td_stage.yml
#
# TD (Test Data) test data for the Staging environment
#
###

token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ
number_of_gameservers: 9

games:
  game_1:
    token: d57d4ed0-d6fb-4d32-9e41-048c8d54ba04
    name: Super Kul Igra
    game_slug: super_kul_igra

  game_2:
    token: 216c07d4-6092-472f-897c-b0a9c47f21f1
    name: QA Test Game
    game_slug: qa_test_game
    number_of_matches: 7 #trenutno ima 3

  game_3:
    token: 56efb5f4-00cc-49ab-a004-2be173313de3
    name: Brisi Brisi
    qame_slug: brisi_brisi
    number_of_matches: 0

gameservers:
  gameserver1:
    token: 216c07d4-6092-472f-897c-b0a9c47f21f1
    id:

ladder:
  ladder1:
    ladder_id: 3401
    name: bd beginner
  auth: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ

known_ladders:
  ladder1_id: 3401
  ladder2_id: 3402
  ladder3_id: 3403

results_info:
  game_slug: colorfrenzy
  page: 0
  size: 10

known_matches:
  match1_id: 48f6690fd053771afc1060f133d1632a
  match2_id: 4d5d4bc841bc08800c09a553cf94f76e
  match3_id: 7796f136c79d8d1012d8be56057c7490

