###
#
# td_stage.yml
#
# TD (Test Data) test data for the Staging environment
#
###

token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ
number_of_gameservers: 10
test_gameserver: 7

    ####Neka izmena da develop bude ispred mastera
