###
#
# td_stage.yml
#
# TD (Test Data) test data for the Staging environment
#
###

token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ
number_of_gameservers: 10
test_gameserver: 7
test_provider: 1

providers:
  provider1:
    id: 3
    name: QABugTestingProvider
    gameservers:
      - id: 21
      - id: 9
      - id: 7

gameservers:
  gameserver1:
    id: 7
    name: qabugtestinggameserver
    package_name: null
    provider_id: 3
    keywords:
    - pogibijaa
  gameserver2:
    token: 216c07d4-6092-472f-897c-b0a9c47f21f1
    id:

ladders:
  ladder1:
    id: 248
    name: test_ladder_1

  ladder2:
    id: 1
    name: test123

  ladder3:
    id: 2
    name: g2

  ladder4:
    id: 5
    name: g3
