###
#
# td_stage.yml
#
# TD (Test Data) test data for the Staging environment
#
###

token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ
number_of_gameservers: 10
test_gameserver: 7
test_provider: 1

providers:
  provider1:
    id: 3
    name: QABugTestingProvider
    gameservers:
      - id: 7

gameservers:
  gameserver1:
    id: 7
    name: qabugtestinggameserver
    package_name: null
    provider_id: 3
    keywords:
      - pogibijaa
