###
#
# td_stage.yml
#
# TD (Test Data) test data for the Staging environment
#
###

token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ
number_of_gameservers: 10
test_gameserver: 7
test_provider: 1

providers:
  provider1:
    id: 3
    name: QABugTestingProvider
    gameservers:
    - id: 7

games:
  game_1:
    token: d57d4ed0-d6fb-4d32-9e41-048c8d54ba04
    name: Super Kul Igra
    game_slug: super_kul_igra

  game_2:
    token: 216c07d4-6092-472f-897c-b0a9c47f21f1
    name: QA Test Game
    game_slug: qa_test_game
    number_of_matches: 7 #trenutno ima 3

  game_3:
    token: 56efb5f4-00cc-49ab-a004-2be173313de3
    name: Brisi Brisi
    qame_slug: brisi_brisi
    number_of_matches: 0

gameservers:
  gameserver1:
    id: 7
    name: qabugtestinggameserver
    package_name: null
    provider_id: 3
    keywords:
    - pogibijaa
  gameserver2:
    token: 216c07d4-6092-472f-897c-b0a9c47f21f1
    id:

ladder:
  ladder1:
    ladder_id: 3401
    name: bd beginner
  auth: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcGlnYXRld2F5QGdhbWVjcmVkaXRzLmNvbSIsInVzZXJJZCI6Ii0xIiwicm9sZSI6IlJPTEVfQURNSU4ifQ.LaAsYurpW-OcuqgfKgHMNcLBtCrduWt2l37cAbWtTUzniTib2EMkVMzeYGSOIe59QHJkcxk1QD-yTnXJ8weKNQ

known_ladders:
  ladder1_id: 3401
  ladder2_id: 3402
  ladder3_id: 3403

results_info:
  game_slug: colorfrenzy
  page: 0
  size: 10

known_matches:
  match1_id: c3748f73a34c1fa974d8705da65d7396
  match2_id: ae66aab37093a90941f37f4eb2e41182
  match3_id: 7f3a034ebc85bb78c152e3f979c35fdf
